# Generated by Django 5.2.8 on 2026-01-24 18:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_loose_kg_product_open_box_remaining_kg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weightsizeallocation',
            name='size',
        ),
        migrations.RemoveField(
            model_name='stockbox',
            name='product',
        ),
        migrations.RemoveField(
            model_name='stockbox',
            name='receipt',
        ),
        migrations.RemoveField(
            model_name='weightsizeallocation',
            name='current_box',
        ),
        migrations.RemoveField(
            model_name='stockreceipt',
            name='product',
        ),
        migrations.RemoveField(
            model_name='stockreceipt',
            name='received_by',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='loose_kg',
            new_name='box_remaining_kg',
        ),
        migrations.RemoveField(
            model_name='product',
            name='open_box_remaining_kg',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sealed_boxes',
        ),
        migrations.AddField(
            model_name='product',
            name='boxes_in_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='is_weighted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='box_weight_kg',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.DeleteModel(
            name='SaleableWeightSize',
        ),
        migrations.DeleteModel(
            name='StockBox',
        ),
        migrations.DeleteModel(
            name='WeightSizeAllocation',
        ),
        migrations.DeleteModel(
            name='StockReceipt',
        ),
    ]
