# Generated by Django 5.2.8 on 2025-12-29 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='apply_vat',
            field=models.BooleanField(default=True),
        ),
    ]
