# Generated by Django 5.2.8 on 2026-01-22 23:34

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_loose_kg_product_open_box_remaining_kg_and_more'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleitem',
            name='weight_size',
        ),
        migrations.AddField(
            model_name='sale',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.15'), max_digits=5),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='weight_price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.productweightprice'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
