# Generated by Django 5.2.8 on 2026-01-24 18:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_remove_saleitem_weight_size_sale_vat_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.04'), max_digits=5),
        ),
    ]
